version: "3.7"

services:
database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=rental-car
    volumes:
        - pgdata:/data/postgres
app:
    build:
    conteiner_name: rental-car
    ports:
        - 3333:3333
    volumes:
        - .:/usr/app

volumes:
    pgdata:
        driver: local
